name: Build
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-versions: ['3.9', '3.8','3.7','3.6']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Install dev dependencies
      run: |
        python -m pip install -r requirements-dev.txt
    - name: Tests with flake8
      run: flake8 src --max-line-length=146
    - name: Tests with mypy
      run: mypy src
